export enum PhaseType {
  GROUP_STAGE = "GROUP_STAGE",
  ROUND_OF_32 = "ROUND_OF_32",
  ROUND_OF_16 = "ROUND_OF_16",
  QUARTER_FINAL = "QUARTER_FINAL",
  SEMI_FINAL = "SEMI_FINAL",
  THIRD_PLACE = "THIRD_PLACE",
  FINAL = "FINAL",
}

export enum MatchStatus {
  SCHEDULED = "SCHEDULED",
  LIVE = "LIVE",
  FINISHED = "FINISHED",
}

export enum MatchEventType {
  GOAL = "GOAL",
  PENALTY_GOAL = "PENALTY_GOAL",
  OWN_GOAL = "OWN_GOAL",
  YELLOW_CARD = "YELLOW_CARD",
  RED_CARD = "RED_CARD",
  SUBSTITUTION = "SUBSTITUTION",
}
